### ISSUE TITLE
The ZendDeveloperTools module issues a warning

### ISSUE THREAD

**Issue by drakulitka** [zendframework/zend-developer-tools#256] opened 2019-01-15 08:52 UTC
After updating PHP to version 7.3, the ZendDeveloperTools module issues a warning:

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /.../vendor/zendframework/zend-developer-tools/src/Options.php on line 102
... on line 105
... on line 108
... on line 111
... on line 114
... on line 338
... on line 345
... on line 348
... on line 366
... on line 369
```

[Image](http://i.piccy.info/i9/1bc87d65be24216c347275cb8ea19549/1547542171/343675/1295079/warning_zdt_php73.jpg)

Please tell me what could be the reason?

**Comment by Ocramius** [comment] 2019-01-15 08:54
Duplicate of https://github.com/zendframework/zend-developer-tools/pull/253

**Closed by Ocramius** 2019-01-15 08:54 UTC
